# Generated by Django 3.2.2 on 2021-09-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionquantity',
            name='position_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
